### ISSUE TITLE
User modes are reported twice

### ISSUE THREAD

**Issue by csmith** [DMDirc/DMDirc#388]
On connecting to DFBnc I see this in the server window:

```
21:35:58 | * User modes are: +i.
21:35:58 | *  sets user mode: +i.
```

The second one shouldn't be there. Those are both using the old formatter.

**Comment by ShaneMcC** [comment]
I don't think this happens anymore? I don't see it anyway.

**Comment by csmith** [comment]
Yeah, old formatter was killed. New one seems to just do it once.
