### ISSUE TITLE
Message command's getLineCount causes NPE

### ISSUE THREAD

**Issue by csmith** [DMDirc/DMDirc#47]
If you try and write a /msg command in a window without an associated Connection, it NPEs:

```
com.dmdirc.commandparser.commands.server.Message in getLineCount at line 119 (application)
com.dmdirc.ui.input.InputHandler in validateText at line 282 (application)
com.dmdirc.ui.input.InputHandler in handleKeyPressed at line 254 (application)
```

Easiest way to repro is to type `/msg x xxx` in the global window.

I'm not sure it makes sense to be validating the command, given it's a server command being executed in a non-server window.

See http://sentry.dmdirc.com/dmdirc/dmdirc/group/259/

**Comment by greboid** [comment]
https://sentry.dmdirc.com/dmdirc/dmdirc/group/326/

seems to be the latest report, same repro steps
