### ISSUE TITLE
DMDirc incorrectly parts channels when quitting

### ISSUE THREAD

**Issue by ShaneMcC** [DMDirc/DMDirc#636]
When closing a server (eg, right clicking on it in the treeview, and going to close), DMDirc closes all the channels (and sends /PARTs) as it closes.

It should instead just send a QUIT.

(The current behaviour is not-so-good for BNC users)

**Comment by csmith** [comment]
Fixed in 2014... See #17.

**Comment by ShaneMcC** [comment]
woo.
